config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :barrooms do
    resource :barroom_users
    resources :messages
  end
  resources :articles
  resources :direct_messages

  root to: "barrooms#index"
end

app/models/barroom.rb
class Barroom < ApplicationRecord
  has_many :barroom_users, dependent: :destroy
  has_many :users, through: :barroom_users
  has_many :messages, dependent: :destroy

  scope :public_channels, ->{ where(direct_message: false) }
  scope :direct_messages, ->{ where(direct_message: true) }

  def self.direct_message_for_users(users)
    user_ids = users.map(&:id).sort
    name = "DM:#{user_ids.join(":")}"

    if barroom = direct_messages.where(name: name).first
      barroom
    else
      #create new barroom
      barroom = new(name: name, direct_message: true)
      barroom.users = users
      barroom.save
      barroom
    end
  end

  def self.unjoined_room(user, barroom)
    BarroomUser.where("user_id = ? AND barroom_id = ?", user, barroom)
  end

end

app/controllers/barrooms_controller.rb
class BarroomsController < ApplicationController
  before_action :set_barroom, only: [:show]

  def index
    @barrooms = Barroom.public_channels
  end

  def show
    @messages = @barroom.messages.order(created_at: :desc).limit(100).reverse
    @barroom_user = current_user.barroom_users.find_by(barroom_id: @barroom.id)
    @barrooms = Barroom.all
  end

  def new
    @barroom = Barroom.new
  end

  def create
    @barroom = Barroom.new(barroom_params)
    respond_to do |format|
      if @barroom.save
        @barroom.barroom_users.where(user_id: current_user.id).first_or_create
        format.html { redirect_to @barroom, notice: 'Barroom was successfully created.' }
        format.json { render :show, status: :created, location: @barroom }
      else
        format.html { render :new }
        format.json { render json: @barroom.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_barroom
      @barroom = Barroom.find(params[:id])
    end

    def barroom_params
      params.require(:barroom).permit(:name)
    end
end

app/helpers/barrooms_helper.rb
module BarroomsHelper
end

app/views/barrooms/_form.html.erb
<%= form_for(barroom) do |f| %>
  <% if barroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(barroom.errors.count, "error") %> prohibited this barroom from being saved:</h2>

      <ul>
      <% barroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/barrooms/index.html.erb
<h1>Barrooms</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @barrooms.each do |barroom| %>
      <tr>
        <td><%= barroom.name %></td>
        <td><%= link_to 'Show', barroom %></td>
        <td><%= link_to 'Edit', edit_barroom_path(barroom) %></td>
        <td><%= link_to 'Destroy', barroom, method: :delete, data: { confirm: 'Are you certain?' }%></td>
        <td><%= link_to 'Join', barroom_barroom_users_path(barroom), method: :post %></td>
        <td><%= link_to 'Leave', barroom_barroom_users_path(barroom), method: :delete %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Barroom', new_barroom_path %>

app/views/barrooms/new.html.erb
<h1>New Bar</h1>

<%= render 'form', barroom: @barroom %>

<%= link_to 'Back', barrooms_path %>

app/views/barrooms/show.html.erb
<div class="top-nav-fixed">
  <h2><%= @barroom.name %></h2>
</div>
<div class="barroom-container" id="msg-container">
  <% unread_messages = false %>
  <div data-behavior='messages' data-barroom-id='<%= @barroom.id %>'>
    <% @messages.each do |message| %>
    <% if !unread_messages && @barroom_user.last_read_at < message.created_at && @barroom_user.user_id != message.user_id %>
    <% unread_messages = true %>
    <div class="strike">
      <span>Unread Messages</span>
    </div>
    <% end %>
      <%= render message %>
    <% end %>
  </div>
</div>
<div class="bottom-nav-fixed" id="contact">
  <%= form_for [@barroom, Message.new] do |f| %>
    <%= f.text_area :body, rows: 1, class: "form-control", autofocus: true %>
  <% end %>
</div>
<script type="text/javascript">
  $(document).on('turbolinks:load', function() {
    function getMessages(msg) {
      var div = $("#msg-container");
      div.scrollTop(div.prop('scrollHeight'));
    }

  $(function() {
    getMessages();
  });
});
</script>