config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :barrooms do
    resource :barroom_users
    resources :messages
  end
  resources :articles
  resources :direct_messages

  root to: "barrooms#index"
end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
<html>
  <head>
    <title>BillsBars</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Ultra" rel="stylesheet">
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-1 col-lg-1" >
          <div class="navbar-fixed-side" id="settings-nav">
          <ul id="affix-settings-nav">
            <% if user_signed_in? %>
              <%= link_to edit_user_registration_path do %>
                <li class="icon-link"><i class="fa fa-user" aria-hidden="true"></i></li>
              <% end %>
              <p class="settings-nav-text">Profile</p>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <li class="icon-link"><i class="fa fa-sign-out" aria-hidden="true"></i></li>
              <% end %>
              <p class="settings-nav-text">Log out</p>
            <% else %>
              <%= link_to new_user_registration_path do %>
                <li class="icon-link"><i class="fa fa-user-plus" aria-hidden="true"></i></li>
              <% end %>
              <p class="settings-nav-text">Sign up</p>
              <%= link_to new_user_session_path do %>
                <li class="icon-link"><i class="fa fa-sign-in" aria-hidden="true"></i></li>
              <% end %>
              <p class="settings-nav-text">Log in</p>
            <% end %>
            <%= link_to articles_path do %>
              <li class="icon-link"><i class="fa fa-newspaper-o" aria-hidden="true"></i></li>
            <% end %>
            <p class="settings-nav-text">News</p>
          </ul>
          </div>
        </div>
        <div class="col-sm-3 col-lg-2">
          <nav class="navbar navbar-default navbar-fixed-side channel-nav">
            <div class="container">
              <div class="navbar-header">
                <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" id="logo-link" href="./"><%= image_tag "logo-thumbnail-c1404c.png", class:"img-responsive", id:"navbar-logo" %></a>
              </div>
              <div class="collapse navbar-collapse" id="messaging-nav">
                <ul class="nav navbar-nav">
                  <% if user_signed_in? %>
                    <li>
                      <!-- <h5 class="nav-headings"> Hi, <%= current_user.username %>!</h5> -->
                    </li>
                    <h5 class="nav-headings">Huddles</h5>
                    <% current_user.barrooms.public_channels.each do |barroom| %>
                      <li class="barroom-link">
                        <%= link_to barroom.name, barroom, data: {behavior: "barroom-link", barroom_id: barroom.id} %>
                        <div class="leave-icon-wrapper">
                          <%= link_to barroom_barroom_users_path(barroom), method: :delete do %>
                            <i class="fa fa-minus-circle" aria-hidden="true"></i>
                          <% end %>
                        </div>
                      </li>
                    <% end %>
                    <hr>
                    <h5 class="nav-headings" id="join-huddle-heading">Join a Huddle</h5>
                    <% @barrooms.each do |barroom| %>
                      <% joined = Barroom.unjoined_room(current_user.id, barroom.id) %>
                      <% if joined.empty? %>
                        <li class="barroom-link">
                          <span id="join-barroom-label"><%= barroom.name %></span>
                          <div class="join-icon-wrapper">
                            <%= link_to barroom_barroom_users_path(barroom), method: :post do %>
                              <i class="fa fa-plus-circle" aria-hidden="true"></i>
                            <% end %>
                          </div>
                        </li>
                      <% end %>
                    <% end %>
                    <hr>
                    <h5 class="nav-headings">Direct Message</h5>
                    <% (User.all - [current_user]).each do |user| %>
                      <li><%= link_to user.username, direct_message_path(user.id), data: {behavior: "barroom-link", barroom_id: Barroom.direct_message_for_users([current_user, user]).id } %></li>
                    <% end %>
                  <% else %>
                  <% end %>
                  <h5 class="nav-headings">Users Online</h5>
                  <% @online_user = User.online %>
                  <% @online_user.each do |online_user| %>
                    <li><a><%= online_user.username %></a></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </nav>
        </div>
        <div class="col-sm-8 col-lg-9" id="main-col">
          <!-- your page content -->
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>
<script type="text/javascript">
  $( document ).on('turbolinks:load', function() {
    $('#affix-settings-nav').affix({
      offset: {
        top: 0
      }
    })
  })
</script>